VFIREWOOD/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using VFIREWOOD.Domain.Core;
using VFIREWOOD.Services.Data;
using VFIREWOOD.Infrastructure.Business;
using VFIREWOOD.Services.Interfaces.Models;
using Microsoft.AspNetCore.Hosting;

namespace VFIREWOOD.Controllers
{
    public class ProductController : Controller
    {
        private IWebHostEnvironment _env;

        private ImageSubCategoryService _imageSubCategoryService;
        private CategoryService _categoryService;
        private SubCategoryService _subCategoryService;
        private ProductService _productService;
        private CheckItemService _checkItemService;
        private CheckService _checkService;
        private OrderService _orderService;

        public ProductController(IWebHostEnvironment env, ImageSubCategoryService imageSubCategoryService, CategoryService categoryService, 
            SubCategoryService subCategoryService, ProductService productService,
            CheckItemService checkItemService, CheckService checkService, OrderService orderService)
        {
            _env = env;

            _imageSubCategoryService = imageSubCategoryService;
            _categoryService = categoryService;
            _subCategoryService = subCategoryService;
            _productService = productService;
            _checkItemService = checkItemService;
            _checkService = checkService;
            _orderService = orderService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Privacy()
        {
            return View();
        }

        public ActionResult Contacts()
        {
            return View();
        }

        public async Task<ActionResult> Discounts()
        {
            var products = await _productService.GetDiscountedProduct();
            var groupedProducts = products.GroupBy(x => x.Name).ToList();
            return View(groupedProducts);
        }

        [Route("Category/{categoryname:maxlength(50)}")]
        public async Task<ActionResult> Category(string categoryname)
        {
            var category = await _categoryService.GetCategoryByName(categoryname);
            if (category == null)
                return View("Error");
            var subCategories = await _subCategoryService.GetSubCategoryByCategoryName(category.Name);
            ViewBag.CategoryRuName = category.RuName;
            return View(subCategories);
        }

        [Route("Category/{categoryname:maxlength(50)}/{subcategoryname:maxlength(50)}")]
        public async Task<ActionResult> SubCategory(string subcategoryname)
        {
            var subCategory = await _subCategoryService.GetSubCategoryByName(subcategoryname);
            if (subCategory == null)
                return View("Error");
            var products = await _productService.GetProductBySubCategoryName(subcategoryname);
            ViewBag.SubCategory = subCategory;
            ViewBag.ImagesSubCategory = await _imageSubCategoryService.GetImageSubCategoryById(subCategory.Id);
            var groupedProducts = products.GroupBy(x => x.Name).ToList();
            
            return View(groupedProducts);
        }

        [Route("Basket")]
        public async Task<ActionResult> Basket()
        {
            IEnumerable<Product> products = new List<Product>();
            var session = HttpContext.Session.GetString("IdProducts");
            if (session != null)
            {
                List<int> idProducts = JsonConvert.DeserializeObject<List<int>>(session);
                products = await _productService.GetProductsByListIds(idProducts);
            }  
            Response.StatusCode = 200;
            ViewBag.Products = products;
            return View();
        }

        [Route("Basket")]
        [HttpPost]
        public async Task<ActionResult> Basket(string jsonprod, Order order)
        {
            if (ModelState.IsValid)
            {
                OrderProcess orderProcess = new OrderProcess(_productService, _orderService, _checkService, _checkItemService);
                ViewOrder viewOrder = await orderProcess.MakeOrder(jsonprod, order);
                HttpContext.Session.Remove("IdProducts");

                if (viewOrder == null)
                {
                    Response.StatusCode = 400;
                    return View("Error");
                }

                var json = JsonConvert.SerializeObject(viewOrder);
                HttpContext.Session.SetString("viewOrder", json);

                EmailService sendEmail = new EmailService();
                string templatePath = System.IO.Path.Combine(_env.WebRootPath, "Templates");
                sendEmail.SendEmail(viewOrder, order.Email, templatePath);
            }
            else
            {
                return View(order);
            }

            Response.StatusCode = 200;
            return RedirectToAction("YourOrder");
        }

        [HttpPost]
        public async Task<string> PutInBasket(int id)
        {
            var product = await _productService.GetProductById(id);
            if (product != null)
            {
                List<int> idProducts = new List<int>();
                var session = HttpContext.Session.GetString("IdProducts");
                if (session != null)
                    idProducts = JsonConvert.DeserializeObject<List<int>>(session);
                if (!idProducts.Contains(id))
                    idProducts.Add(product.Id);
                var json = JsonConvert.SerializeObject(idProducts);
                HttpContext.Session.SetString("IdProducts", json);
                Response.StatusCode = 200;
                return "in stock";
            }
            Response.StatusCode = 200;
            return "not available";
        }

        [HttpPost]
        public string RemoveProductFromBasket(int? id)
        {
            if (id != null)
            {
                List<int> idProducts = new List<int>();
                idProducts = JsonConvert.DeserializeObject<List<int>>(HttpContext.Session.GetString("IdProducts"));
                idProducts.Remove(id.Value);
                var json = JsonConvert.SerializeObject(idProducts);
                HttpContext.Session.SetString("IdProducts", json);
            }
            Response.StatusCode = 200;
            return "removed";
        }

        [Route("YourOrder")]
        public ActionResult YourOrder()
        {
            if (HttpContext.Session.GetString("viewOrder") != null)
            {
                ViewOrder viewOrder = JsonConvert.DeserializeObject<ViewOrder>(HttpContext.Session.GetString("viewOrder"));
                HttpContext.Session.Remove("viewOrder");
                Response.StatusCode = 200;
                return View(viewOrder);
            }
            Response.StatusCode = 200;
            return RedirectToAction("Index", "Home");
        }
    }
}

VFIREWOOD/ViewComponents/CategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using VFIREWOOD.Domain.Core;
using VFIREWOOD.Services.Data;

namespace VFIREWOOD.ViewComponents
{
    public class CategoryViewComponent : ViewComponent
    {
        private CategoryService _categoryService;
        private SubCategoryService _subCategoryService;
        public CategoryViewComponent(CategoryService categoryService, SubCategoryService subCategoryService)
        {
            _categoryService = categoryService;
            _subCategoryService = subCategoryService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _categoryService.GetCategoryList();
            var subCategories = await _subCategoryService.GetSubCategoryList();

            foreach (var cat in categories)
            {
                cat.SubCategories = new List<SubCategory>();
                foreach (var sub in subCategories)
                { 
                    if (cat.Name == sub.CategoryName)
                    {
                        cat.SubCategories.Add(sub);
                    }
                }
            }
            return View(categories);
        }
    }
}

VFIREWOOD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FaneraLes-Torg</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/nesteddropdown.css" asp-append-version="true" />
    @{
        ViewBag.countProduct = 0;
        var session = Context.Session.GetString("IdProducts");
        if (session != null)
        {
            ViewBag.countProduct = JsonConvert.DeserializeObject<List<int>>(session).Count;
        }
    }
    <style>
        body {
            height: 100%;
            background-image: url('/images/oak_background.jpg');
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
    </style>
    <script src="//code.jivosite.com/widget/bfMcBRgspx" async></script>
</head>
<body>
    <header>
        @*         <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"> *@
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark box-shadow" style="background-color:brown">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FaneraLes-Torg</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @await Component.InvokeAsync("Category")
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                            @* <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="About">О нас</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Product" asp-action="Contacts">Контанты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Product" asp-action="Discounts">Скидки</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Product" asp-action="Basket"><img style="width:24px; height:24px;" src="~/images/cartbasket.png" /><label id="basket_label">@ViewBag.countProduct</label></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div id="myContainer" class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-light" style="background-color:brown;">
        <div class="container">
            &copy; 2021 - FaneraLes-Torg
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/nesteddropdownjs.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false);
</body>
</html>